/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/gurupras/flutter-librsync */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "librsync.go"

#include <stdint.h>
#include <stdlib.h>

typedef int64_t (*rs_read_fn_t)(void* ctx, uint8_t* buf, int64_t len);
typedef int64_t (*rs_seek_fn_t)(void* ctx, int64_t offset, int32_t whence);
typedef int64_t (*rs_write_fn_t)(void* ctx, const uint8_t* buf, int64_t len);

// Sequential reader (no seek; used for signature input, new-data input, delta input)
typedef struct {
    rs_read_fn_t read;
    void*        ctx;
} rs_reader_t;

// Seekable reader (used for patch base)
typedef struct {
    rs_read_fn_t read;
    rs_seek_fn_t seek;
    void*        ctx;
} rs_read_seeker_t;

// Writer (used for all outputs)
typedef struct {
    rs_write_fn_t write;
    void*         ctx;
} rs_writer_t;

// Inline helpers to call through function pointers.
// CGO does not allow calling C function pointers directly from Go,
// so we use static inline trampolines.
static inline int64_t _rs_read(rs_reader_t* r, uint8_t* buf, int64_t len) {
    return r->read(r->ctx, buf, len);
}
static inline int64_t _rs_rs_read(rs_read_seeker_t* r, uint8_t* buf, int64_t len) {
    return r->read(r->ctx, buf, len);
}
static inline int64_t _rs_seek(rs_read_seeker_t* r, int64_t offset, int32_t whence) {
    return r->seek(r->ctx, offset, whence);
}
static inline int64_t _rs_write(rs_writer_t* w, const uint8_t* buf, int64_t len) {
    return w->write(w->ctx, buf, len);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* librsync_signature(rs_reader_t* input, rs_writer_t* output, uint32_t blockLen, uint32_t strongLen, uint32_t sigType);
extern char* librsync_delta(rs_reader_t* sigInput, rs_reader_t* newData, rs_writer_t* output);
extern char* librsync_patch(rs_read_seeker_t* base, rs_reader_t* delta, rs_writer_t* output);
extern void librsync_free_string(char* s);
extern uint32_t librsync_blake2_sig_magic(void);
extern uint32_t librsync_md4_sig_magic(void);

#ifdef __cplusplus
}
#endif
