/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/gurupras/flutter-librsync */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "librsync.go"

#include <stdint.h>
#include <stdlib.h>

typedef int64_t (*rs_read_fn_t)(void* ctx, uint8_t* buf, int64_t len);
typedef int64_t (*rs_seek_fn_t)(void* ctx, int64_t offset, int32_t whence);
typedef int64_t (*rs_write_fn_t)(void* ctx, const uint8_t* buf, int64_t len);

// Sequential reader (no seek; used for signature input, new-data input, delta input)
typedef struct {
    rs_read_fn_t read;
    void*        ctx;
} rs_reader_t;

// Seekable reader (used for patch base)
typedef struct {
    rs_read_fn_t read;
    rs_seek_fn_t seek;
    void*        ctx;
} rs_read_seeker_t;

// Writer (used for all outputs)
typedef struct {
    rs_write_fn_t write;
    void*         ctx;
} rs_writer_t;

// Inline helpers to call through function pointers.
// CGO does not allow calling C function pointers directly from Go,
// so we use static inline trampolines.
static inline int64_t _rs_read(rs_reader_t* r, uint8_t* buf, int64_t len) {
    return r->read(r->ctx, buf, len);
}
static inline int64_t _rs_rs_read(rs_read_seeker_t* r, uint8_t* buf, int64_t len) {
    return r->read(r->ctx, buf, len);
}
static inline int64_t _rs_seek(rs_read_seeker_t* r, int64_t offset, int32_t whence) {
    return r->seek(r->ctx, offset, whence);
}
static inline int64_t _rs_write(rs_writer_t* w, const uint8_t* buf, int64_t len) {
    return w->write(w->ctx, buf, len);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// librsync_signature generates an rsync signature.
//
// input    – sequential reader for the basis file
// output   – writer for the signature data
// blockLen – block length for checksumming (e.g. 2048)
// strongLen – strong hash length in bytes (e.g. 32 for BLAKE2)
// sigType  – magic number: BLAKE2_SIG_MAGIC (0x72730137) or MD4_SIG_MAGIC (0x72730136)
//
// Returns NULL on success, or a heap-allocated C string describing the error.
// The caller must free the returned string with librsync_free_string.
//
extern char* librsync_signature(rs_reader_t* input, rs_writer_t* output, uint32_t blockLen, uint32_t strongLen, uint32_t sigType);

// librsync_delta generates a delta between a signature and new file data.
//
// sigInput – sequential reader for the signature produced by librsync_signature
// newData  – sequential reader for the new (modified) file
// output   – writer for the delta data
//
// Returns NULL on success, or a heap-allocated error string (free with librsync_free_string).
//
extern char* librsync_delta(rs_reader_t* sigInput, rs_reader_t* newData, rs_writer_t* output);

// librsync_patch reconstructs a new file by applying a delta to a base file.
//
// base   – seekable reader for the basis file (must support random access)
// delta  – sequential reader for the delta produced by librsync_delta
// output – writer for the reconstructed file
//
// Returns NULL on success, or a heap-allocated error string (free with librsync_free_string).
//
extern char* librsync_patch(rs_read_seeker_t* base, rs_reader_t* delta, rs_writer_t* output);

// librsync_free_string frees a C string returned by any librsync_* function.
//
extern void librsync_free_string(char* s);

// librsync_blake2_sig_magic returns the BLAKE2 signature magic number.
//
extern uint32_t librsync_blake2_sig_magic();

// librsync_md4_sig_magic returns the MD4 signature magic number (deprecated).
//
extern uint32_t librsync_md4_sig_magic();

#ifdef __cplusplus
}
#endif
