/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/gurupras/flutter-librsync */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "librsync.go"

#include <stdint.h>
#include <stdlib.h>

// Callback struct for random-access reads on the base file.
// Dart allocates this with calloc and keeps it alive for the patch session.
typedef struct {
    void* userdata;
    int32_t (*read_at)(void* userdata, int64_t offset, uint8_t* buf, size_t len, size_t* bytes_read);
} rs_read_seeker_t;

// Trampoline so Go can call the function pointer without unsafe casts.
static int32_t call_read_at(const rs_read_seeker_t* rs, int64_t offset, uint8_t* buf, size_t len, size_t* bytes_read) {
    return rs->read_at(rs->userdata, offset, buf, len, bytes_read);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* librsync_strerror(int32_t code);
extern void librsync_free(void* ptr);
extern int32_t librsync_signature(uint8_t* inputPtr, size_t inputLen, uint32_t blockLen, uint32_t strongLen, uint32_t sigType, uint8_t** outPtr, size_t* outLen);
extern int32_t librsync_delta(uint8_t* sigPtr, size_t sigLen, uint8_t* inputPtr, size_t inputLen, uint8_t** outPtr, size_t* outLen);
extern int32_t librsync_patch(uint8_t* basePtr, size_t baseLen, uint8_t* deltaPtr, size_t deltaLen, uint8_t** outPtr, size_t* outLen);
extern intptr_t librsync_sig_parse(uint8_t* sigPtr, size_t sigLen);
extern void librsync_sig_free(intptr_t handle);
extern intptr_t librsync_signature_new(uint32_t blockLen, uint32_t strongLen, uint32_t sigType);
extern int32_t librsync_signature_feed(intptr_t handle, uint8_t* inputPtr, size_t inputLen, uint8_t** outPtr, size_t* outLen);
extern int32_t librsync_signature_end(intptr_t handle, uint8_t** outPtr, size_t* outLen);
extern void librsync_signature_free(intptr_t handle);
extern intptr_t librsync_delta_new(intptr_t sigHandle);
extern int32_t librsync_delta_feed(intptr_t handle, uint8_t* inputPtr, size_t inputLen, uint8_t** outPtr, size_t* outLen);
extern int32_t librsync_delta_end(intptr_t handle, uint8_t** outPtr, size_t* outLen);
extern void librsync_delta_free(intptr_t handle);
extern intptr_t librsync_patch_new(rs_read_seeker_t* rs);
extern int32_t librsync_patch_feed(intptr_t handle, uint8_t* deltaPtr, size_t deltaLen);
extern int32_t librsync_patch_end(intptr_t handle, uint8_t** outPtr, size_t* outLen);
extern void librsync_patch_free(intptr_t handle);

#ifdef __cplusplus
}
#endif
